Gradle Version, TargetSdk, CompileSdk Upgraded and VersionCatalogs Implemented
readium/kotlin-toolkit pull request #265
Opened 2022-08-22 20:45 UTC by svlilyas

- Gradle version upgraded to 7.4.2 and Android Gradle Plugin upgraded to 7.2.2
- TargetSdk and CompileSdk upgraded to 32
- buildSrc added to manage Plugins and common Android Configs
- VersionCatalogs implemented with TOML file
- TOML file updated

2022-08-26 11:02 UTC, mickael-menu requested changes
@svlilyas Thank you for taking the time to submit a PR, there's good stuff in it. However, please open an issue (or a Slack message) first next time to discuss the changes, to make sure you don't waste your time on work that won't be accepted.

I left a few comments, but could you also rebase your changes to merge the PR onto the `develop` branch? We only merge hotfixes on `main`, any other changes must be on `develop`.

2022-08-30 18:44 UTC, svlilyas commented on buildSrc/src/main/kotlin/Fields.kt
> +}
These used for Flavors based Fields. For example if you want to use SERVICE_URL in UAT Flavor then you need to define there. You can use different values for same variable according to Flavors.

2022-08-30 18:46 UTC, svlilyas commented on gradle.properties
> +android.disableAutomaticComponentCreation=true
It is just for removing the warning about automatic creation to maven publish.

2022-08-30 18:48 UTC, svlilyas commented on buildSrc/src/main/kotlin/ModuleDependency.kt
> +    }
You are right, this is just for managing modules. I just use one method here to not hard code module names in Gradle. 
Typing "implementation(data())" is so easy.

2022-08-30 18:50 UTC, svlilyas commented on buildSrc/src/main/kotlin/AndroidConfig.kt
> +        const val MAIN = "main"
As you know Flavors are different from BuildTypes to manage UAT, PILOT, STORE etc. cases.

2022-08-30 18:51 UTC, svlilyas commented on gradle/libs.versions.toml
> -# Eventually want to use this for dependencies, but Android Studio is not ready
Nope, unfortunately it is not fully supported to see if there are outdated dependencies :(

2022-09-01 12:28 UTC, mickael-menu commented on gradle.properties
> +android.disableAutomaticComponentCreation=true
Alright

2022-09-01 12:31 UTC, mickael-menu commented on buildSrc/src/main/kotlin/AndroidConfig.kt
> +        const val MAIN = "main"
Right, but we don't need or use flavors in Readium, so we can remove most of this code.

2022-09-01 12:32 UTC, mickael-menu commented on buildSrc/src/main/kotlin/ModuleDependency.kt
> +    }
I'd prefer keeping only the code that is actually used in the build configs.

2022-09-01 12:33 UTC, mickael-menu commented on buildSrc/src/main/kotlin/Fields.kt
> +}
We don't use flavors so we can remove the fields.

2022-09-09 14:51 UTC, svlilyas commented
I could not able to find rebase settings. Can you tell me how to do it?

2022-09-09 14:54 UTC, mickael-menu commented
I changed the base branch of your PR to `develop`, try running `git merge develop` from your clone and fix any conflict you will probably get. This or alternatively you can start again from `develop` with a new PR and copy your changes there.

2022-09-18 17:39 UTC, closed without merging

2022-09-21 15:37 UTC, mickael-menu commented
@svlilyas Looks like Android Studio Dolphin has better support for TOML version catalogs 👍