Add ktlint-gradle and reformat code
readium/kotlin-toolkit pull request #300
Opened 2022-11-17 11:48 UTC by qnga

2022-11-18 09:48 UTC, mickael-menu requested changes
Could you open a new PR starting from `develop` instead of the settings branch? This won't be easily mergeable with https://github.com/readium/kotlin-toolkit/pull/293 as the PRs are squashed into a single commit.

2022-11-18 09:53 UTC, qnga commented
There would be many conflicts if I reformat the code from `develop`. I'll be able to rebase it upon `develop` and force-push it when #293 has been merged instead.

2022-11-18 10:02 UTC, mickael-menu commented
Sounds good

2022-11-28 12:00 UTC, mickael-menu approved these changes

2022-11-28 12:00 UTC, merged